version: '3'
services:
  jupyterlab:
    build: "./"
    image: "jupyterlab:3.9.10"
    container_name: jupyterlab
    restart: always
    ports:
      - "8888:8888"
      - "2222:22"
      - "6006:6006"
    volumes:
      - /data:/data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    privileged: true
    shm_size: "8gb"
    tty: true
