version: '3'
services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
    image: "jupyterlab:main"
    container_name: jupyterlab_main
    restart: always
    ports:
      - "8889:8888"
      - "2223:22"
      - "6006:6006"
    volumes:
      - /data:/data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    privileged: true
    shm_size: '8gb'
